"""Added Dict table

Revision ID: a9b1d5881adb
Revises: 50a55cea1043
Create Date: 2024-06-16 10:13:41.626290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b1d5881adb'
down_revision: Union[str, None] = '50a55cea1043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ste_name', sa.String(), nullable=False),
    sa.Column('characteristics_name', sa.String(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('final_category_directory', sa.String(), nullable=False),
    sa.Column('kpgz_code', sa.String(), nullable=False),
    sa.Column('kpgz', sa.String(), nullable=False),
    sa.Column('spgz_code', sa.Float(), nullable=False),
    sa.Column('spgz', sa.String(), nullable=False),
    sa.Column('registry_number_rk', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dict'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dict')
    # ### end Alembic commands ###
