"""Added Contract table

Revision ID: 435f73519706
Revises: f8387b0f5271
Create Date: 2024-06-16 11:19:11.617282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435f73519706'
down_revision: Union[str, None] = 'f8387b0f5271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id_spgz', sa.Float(), nullable=True),
    sa.Column('name_spgz', sa.String(), nullable=True),
    sa.Column('registry_number_rk', sa.String(), nullable=True),
    sa.Column('lot_number_procurement', sa.Float(), nullable=True),
    sa.Column('ikz', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('subject_gk_name', sa.String(), nullable=True),
    sa.Column('supplier_selection_method', sa.String(), nullable=True),
    sa.Column('contract_basis_single_supplier', sa.String(), nullable=True),
    sa.Column('contract_status', sa.String(), nullable=True),
    sa.Column('version_number', sa.Float(), nullable=True),
    sa.Column('gk_price_rub', sa.Float(), nullable=True),
    sa.Column('gk_price_at_signing_rub', sa.Float(), nullable=True),
    sa.Column('paid_rub', sa.Float(), nullable=True),
    sa.Column('paid_percent', sa.Float(), nullable=True),
    sa.Column('final_kpgz_code', sa.String(), nullable=True),
    sa.Column('final_kpgz_name', sa.String(), nullable=True),
    sa.Column('contract_date', sa.DateTime(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_change_date', sa.DateTime(), nullable=True),
    sa.Column('execution_start_date', sa.DateTime(), nullable=True),
    sa.Column('execution_end_date', sa.DateTime(), nullable=True),
    sa.Column('contract_end_date', sa.DateTime(), nullable=True),
    sa.Column('supplier_sme_status_at_contract_signing', sa.String(), nullable=True),
    sa.Column('supplier_region_name', sa.String(), nullable=True),
    sa.Column('law_basis_44_223', sa.Float(), nullable=True),
    sa.Column('electronic_execution', sa.String(), nullable=True),
    sa.Column('fulfilled_by_supplier', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
