"""Added Turnover table

Revision ID: 50a55cea1043
Revises: 7fab97dca9b1
Create Date: 2024-06-16 09:50:14.011982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a55cea1043'
down_revision: Union[str, None] = '7fab97dca9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turnover',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('unit_of_measurement', sa.String(), nullable=False),
    sa.Column('quantity_start_debit', sa.Float(), nullable=False),
    sa.Column('balance_start_debit', sa.Float(), nullable=False),
    sa.Column('quantity_turnover_debit', sa.Float(), nullable=False),
    sa.Column('turnover_debit', sa.Float(), nullable=False),
    sa.Column('quantity_turnover_credit', sa.Float(), nullable=False),
    sa.Column('turnover_credit', sa.Float(), nullable=False),
    sa.Column('quantity_end_debit', sa.Float(), nullable=False),
    sa.Column('balance_end_debit', sa.Float(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('quarter_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turnover'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turnover')
    # ### end Alembic commands ###
