"""Added nullable

Revision ID: f8387b0f5271
Revises: a9b1d5881adb
Create Date: 2024-06-16 10:39:20.218177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8387b0f5271'
down_revision: Union[str, None] = 'a9b1d5881adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dict', 'ste_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dict', 'characteristics_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dict', 'reference_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('dict', 'final_category_directory',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dict', 'kpgz_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dict', 'kpgz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dict', 'spgz_code',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('dict', 'spgz',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dict', 'registry_number_rk',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('turnover', 'product',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('turnover', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('turnover', 'unit_of_measurement',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('turnover', 'quantity_start_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('turnover', 'balance_start_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('turnover', 'quantity_turnover_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('turnover', 'turnover_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('turnover', 'quantity_turnover_credit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('turnover', 'turnover_credit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('turnover', 'quantity_end_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('turnover', 'balance_end_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('turnover', 'account_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('turnover', 'quarter_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('turnover', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('turnover', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('turnover', 'quarter_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('turnover', 'account_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('turnover', 'balance_end_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('turnover', 'quantity_end_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('turnover', 'turnover_credit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('turnover', 'quantity_turnover_credit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('turnover', 'turnover_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('turnover', 'quantity_turnover_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('turnover', 'balance_start_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('turnover', 'quantity_start_debit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('turnover', 'unit_of_measurement',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('turnover', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('turnover', 'product',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dict', 'registry_number_rk',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('dict', 'spgz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dict', 'spgz_code',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('dict', 'kpgz',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dict', 'kpgz_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dict', 'final_category_directory',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dict', 'reference_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('dict', 'characteristics_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dict', 'ste_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
