"""added tg username

Revision ID: 8719ac2f5092
Revises: 54c3460d1fd5
Create Date: 2024-06-23 19:43:44.434279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8719ac2f5092'
down_revision: Union[str, None] = '54c3460d1fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user', sa.Column('telegram_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_user', 'telegram_username')
    # ### end Alembic commands ###
