"""create user table

Revision ID: 16f7056a12d9
Revises: 
Create Date: 2024-06-08 18:18:31.464948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f7056a12d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('keycloak_id', sa.UUID(), nullable=True),
    sa.Column('verification_code', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_user'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_user')
    # ### end Alembic commands ###
