"""Added Instutution relation for contracts

Revision ID: 4e536ca0124d
Revises: 305b35cc87ab
Create Date: 2024-06-16 17:39:50.769299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e536ca0124d'
down_revision: Union[str, None] = '305b35cc87ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('institution_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_contracts_institution_id_institution'), 'contracts', 'institution', ['institution_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_contracts_institution_id_institution'), 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'institution_id')
    # ### end Alembic commands ###
